name: Build/Deploy Sample.Worker

on:
  push:
    branches: 
      [ master ]
    paths:
    - 'src/Sample.Worker/**'
    - 'src/Sample.Shared/**'
    - '.github/workflows/BuildDeployWorker.yml'

  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: masstransitcontainers.azurecr.io/containerapps/worker
          username: ${{ secrets.SAMPLECONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SAMPLECONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: masstransitcontainers.azurecr.io/containerapps/worker:${{ github.sha }}
          file: ./src/Dockerfile.worker
          context: ./src


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLECONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sample-worker -g SampleContainerApps --server masstransitcontainers.azurecr.io --username  ${{ secrets
            .SAMPLECONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.SAMPLECONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n sample-worker -g SampleContainerApps --image masstransitcontainers.azurecr.io/containerapps/worker:${{ github.sha }}
