name: Trigger auto deployment for sample-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'src/**'
    - '.github/workflows/sample-containerapp-AutoDeployTrigger-af30a5f0-f164-40da-a3b7-7918c0fc9a0b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: masstransitcontainers.azurecr.io/containerapps/api
          username: ${{ secrets.SAMPLECONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SAMPLECONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: masstransitcontainers.azurecr.io/containerapps/api/sample-containerapp:${{ github.sha }}
          file: ./src/Dockerfile.api
          context: ./src


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLECONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sample-containerapp -g SampleContainerApps --server masstransitcontainers.azurecr.io/containerapps/api --username  ${{ secrets.SAMPLECONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.SAMPLECONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n sample-containerapp -g SampleContainerApps --image masstransitcontainers.azurecr.io/containerapps/api/sample-containerapp:${{ github.sha }}
